In [27]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

In [19]:
#Import txt檔
f = open("/docker_workplace/globes-3.2.18/examples/best_fit_spectrum_deltacp_theta23_grid_mse.dat")

In [20]:
theta12_true = []
theta13_true = []
theta23_true = []
delta_true = []
sdm_true = []
ldm_true = []

theta23_initial = []
delta_initial = []
chi2 = []

theta12_fit = []
theta13_fit = []
theta23_fit = []
delta_fit = []
sdm_fit = []
ldm_fit = []

while True:
    s = [float(c) for c in f.readline().split()]
    if(len(s)>0):
        theta12_true.append(s[0])
        theta13_true.append(s[1])
        theta23_true.append(s[2])
        delta_true.append(s[3])
        sdm_true.append(s[4])
        ldm_true.append(s[5])
        theta23_initial.append(s[6])
        delta_initial.append(s[7])
        chi2.append(s[8])
        theta12_fit.append(s[9])
        theta13_fit.append(s[10])
        theta23_fit.append(s[11])
        delta_fit.append(s[12])
        sdm_fit.append(s[13])
        ldm_fit.append(s[14])
    else:
        break    

In [21]:
#輸出全部資料為npz檔
np.savez("/docker_workplace/globes-3.2.18/examples/python/output/best_fit_spectrum_deltacp_theta23_grid_mse",
        theta12_true = theta12_true,
        theta13_true = theta13_true,
        theta23_true = theta23_true,
        delta_true = delta_true,
        sdm_true = sdm_true,
        ldm_true = ldm_true,
        theta23_initial = theta23_initial,
        delta_initial = delta_initial,
        chi2 = chi2,
        theta12_fit = theta12_fit,
        theta13_fit = theta13_fit,
        theta23_fit = theta23_fit,
        delta_fit = delta_fit,
        sdm_fit = sdm_fit,
        ldm_fit = ldm_fit
        )

# Test

In [22]:
data = np.load('/docker_workplace/globes-3.2.18/examples/python/output/best_fit_spectrum_deltacp_theta23_grid_mse.npz')

In [23]:
data.files

['theta12_true',
 'theta13_true',
 'theta23_true',
 'delta_true',
 'sdm_true',
 'ldm_true',
 'theta23_initial',
 'delta_initial',
 'chi2',
 'theta12_fit',
 'theta13_fit',
 'theta23_fit',
 'delta_fit',
 'sdm_fit',
 'ldm_fit']

In [24]:
data['theta23_initial']

array([40., 40., 40., ..., 50., 50., 50.])

In [25]:
data['delta_initial']

array([  0.,   9.,  18., ..., 342., 351., 360.])

In [26]:
data['chi2']

array([304.211, 340.452, 287.797, ..., 320.18 , 280.768, 299.5  ])

In [27]:
len(data['chi2'])

1681

# For Loop

In [13]:
for i in range(100):
    #Import txt檔
    f = open("/docker_workplace/globes-3.2.18/examples/sample_grid/best_fit_spectrum_deltacp_theta23_grid_mse_ver"+str(i+1)+".dat")
    theta12_true = []
    theta13_true = []
    theta23_true = []
    delta_true = []
    sdm_true = []
    ldm_true = []

    theta23_initial = []
    delta_initial = []
    chi2 = []

    theta12_fit = []
    theta13_fit = []
    theta23_fit = []
    delta_fit = []
    sdm_fit = []
    ldm_fit = []

    while True:
        s = [float(c) for c in f.readline().split()]
        if(len(s)>0):
            theta12_true.append(s[0])
            theta13_true.append(s[1])
            theta23_true.append(s[2])
            delta_true.append(s[3])
            sdm_true.append(s[4])
            ldm_true.append(s[5])
            theta23_initial.append(s[6])
            delta_initial.append(s[7])
            chi2.append(s[8])
            theta12_fit.append(s[9])
            theta13_fit.append(s[10])
            theta23_fit.append(s[11])
            delta_fit.append(s[12])
            sdm_fit.append(s[13])
            ldm_fit.append(s[14])
        else:
            break    
    #輸出全部資料為npz檔
    np.savez("/docker_workplace/globes-3.2.18/examples/python/output/sample_grid/best_fit_spectrum_deltacp_theta23_grid_mse_ver"+str(i+1),
            theta12_true = theta12_true,
            theta13_true = theta13_true,
            theta23_true = theta23_true,
            delta_true = delta_true,
            sdm_true = sdm_true,
            ldm_true = ldm_true,
            theta23_initial = theta23_initial,
            delta_initial = delta_initial,
            chi2 = chi2,
            theta12_fit = theta12_fit,
            theta13_fit = theta13_fit,
            theta23_fit = theta23_fit,
            delta_fit = delta_fit,
            sdm_fit = sdm_fit,
            ldm_fit = ldm_fit
            )

In [23]:
data = np.load('/docker_workplace/globes-3.2.18/examples/python/output/sample_grid/best_fit_spectrum_deltacp_theta23_grid_mse_ver95.npz')

In [24]:
data.files

['theta12_true',
 'theta13_true',
 'theta23_true',
 'delta_true',
 'sdm_true',
 'ldm_true',
 'theta23_initial',
 'delta_initial',
 'chi2',
 'theta12_fit',
 'theta13_fit',
 'theta23_fit',
 'delta_fit',
 'sdm_fit',
 'ldm_fit']

In [25]:
data['theta23_true']

array([0.817098, 0.817098, 0.817098, ..., 0.817098, 0.817098, 0.817098])

In [26]:
data['delta_true']

array([249.436, 249.436, 249.436, ..., 249.436, 249.436, 249.436])

In [16]:
data['theta23_initial']

array([40., 40., 40., ..., 50., 50., 50.])

In [17]:
data['delta_initial']

array([  0.,   9.,  18., ..., 342., 351., 360.])

In [18]:
data['chi2']

array([405.711, 379.148, 324.356, ..., 282.221, 323.2  , 321.459])

In [19]:
len(data['chi2'])

1681